import random
import os

guesses=0
randNum=random.randint(1,100)
userGuess=None
print("\n ***************** NUMBER GUESSING GAME *****************\n")
print("RULES : \n*You will be asked to guess a number generated by cpu.\n*If you guess higher or lower that the actual number you will be told so.\n*Try to guess the number in minimum number of guesses.\n ")
with open ("hiscore.txt") as f:
    hiscore=int(f.read())
print(f"\nHighscore : {hiscore} Guesses\n\n")

input("\t\t\t Press enter to start")



while(userGuess!=randNum):
    os.system("clear")
    userGuess=int(input("Enter your guess : "))
    if(userGuess==randNum):
        print("You guessed it right!")
    else:
        if(userGuess>randNum):
            print("Number is lower")
        elif(userGuess<randNum):
            print("Number is lower")


print(f"\nYou guesses the number in {guesses} guesses.")

    
if(guesses<hiscore):
    print("\nNew Highscore !")
    print(f"{guesses} guess(es)")
    with open("hiscore.txt","w") as f:
        f.write(str(guesses))