# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alexanew.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 600, 750))
        self.bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 600, 750))
        self.label_2.setMaximumSize(QtCore.QSize(600, 750))
        self.label_2.setStyleSheet("color: Black;\n"
"border : 2px Solid White;")
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 320, 61, 21))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Mongolian Baiti\";\n"
"border: 2px Solid Green;\n"
"border-color: rgb(28, 255, 25);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 360, 61, 21))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Mongolian Baiti\";\n"
"border: 2px Solid Red;\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gui_1 = QtWidgets.QLabel(self.centralwidget)
        self.gui_1.setGeometry(QtCore.QRect(10, 50, 281, 241))
        self.gui_1.setStyleSheet("\n"
"background-color: rgb(255, 203, 178);")
        self.gui_1.setText("")
        self.gui_1.setPixmap(QtGui.QPixmap("../../PycharmProjects/pythonProject/blackwomen.gif"))
        self.gui_1.setScaledContents(True)
        self.gui_1.setObjectName("gui_1")
        self.gui_2 = QtWidgets.QLabel(self.centralwidget)
        self.gui_2.setGeometry(QtCore.QRect(300, 50, 211, 111))
        self.gui_2.setStyleSheet("background-color: rgb(0,0,0);\n"
"border-color: rgb(255, 255, 255);\n"
"border: 1px Solid White")
        self.gui_2.setText("")
        self.gui_2.setPixmap(QtGui.QPixmap("../../PycharmProjects/pythonProject/soundwaves.gif"))
        self.gui_2.setScaledContents(True)
        self.gui_2.setObjectName("gui_2")
        self.terminal = QtWidgets.QLabel(self.centralwidget)
        self.terminal.setGeometry(QtCore.QRect(10, 299, 350, 200))
        self.terminal.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"border: 2px Solid White;")
        self.terminal.setText("")
        self.terminal.setObjectName("terminal")
        self.terminal.setPixmap(QtGui.QPixmap("../../PycharmProjects/pythonProject/alexa.gif"))
        self.gui_3 = QtWidgets.QLabel(self.centralwidget)
        self.gui_3.setGeometry(QtCore.QRect(300, 180, 211, 111))
        self.gui_3.setStyleSheet("background-color: rgb(0,0,0);\n"
"border-color: rgb(255, 255, 255);\n"
"border: 1px Solid White")
        self.gui_3.setText("")
        self.gui_3.setPixmap(QtGui.QPixmap("../../PycharmProjects/pythonProject/systeminitial.gif"))
        self.gui_3.setScaledContents(True)
        self.gui_3.setObjectName("gui_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "START"))
        self.pushButton_3.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
